---
# tasks file for install limesurvey
- name: LIMESURVEY SOURCE | Clone repository
  ansible.builtin.git:
    repo: https://github.com/LimeSurvey/limesurvey.git
    version: "{{ limesurvey_version }}"
    depth: 1
    dest: "/usr/local/src/limesurvey_{{ limesurvey_version }}"

- name: LIMESURVEY WEB DIR | Create LimeSurvey install directory
  ansible.builtin.file:
    dest: "{{ limesurvey_http_rootdir }}/{{ limesurvey_domain }}/"
    state: directory
    owner: "{{ limesurvey_http_user }}"
    group: "{{ limesurvey_http_group }}"
    recurse: true

- name: LIMESURVEY WEB DIR | Synchronize source code to web server directory
  ansible.posix.synchronize:
    src: "/usr/local/src/limesurvey_{{ limesurvey_version }}/"
    dest: "{{ limesurvey_http_rootdir }}/{{ limesurvey_domain }}/"
  delegate_to: "{{ inventory_hostname }}"

- name: LIMESURVEY CONF | Create empty configuration file
  ansible.builtin.template:
    src: "config.php.j2"
    dest: "{{ limesurvey_http_rootdir }}/{{ limesurvey_domain }}/conf/conf.php"
    owner: "{{ limesurvey_http_user }}"
    group: "{{ limesurvey_http_group }}"

- name: LIMESURVEY WEB DIR | Set web server owner of limesurvey files
  ansible.builtin.file:
    path: "{{ limesurvey_http_rootdir }}/{{ limesurvey_domain }}"
    owner: "{{ limesurvey_http_user }}"
    group: "{{ limesurvey_http_group }}"
    mode: '0755'
